### PR TITLE
Community - fix non-existing post 404

### LINKED ISSUE #3340: non-existing posts do not result in 404
This seems to be new behavior:

https://steemit.com/dontexist/@abc/this-post-doesnt-exist
image

### PR DESCRIPTION
**Pull request by roadscape**
From @economicstudio #3354:

> Fix #3340
> 
> non-existing post 404
> 
> 
> 
> The bug was due to `if (!dis) return null;` not rendering 404 page.
> 
> ps. Eventually, it might be better to be handled by `RootRoute.js` or somewhere centrally, but that may need some substantial change, so I rather fixed the existing `Post.jsx` only.

### CODE REVIEW

File: src/app/components/pages/Post.jsx [hunk 1]
```diff
@@ -63,7 +65,47 @@ class Post extends React.Component {
         }
         const dis = content.get(post);
```
Comment (JonathanPorta) [inline src/app/components/pages/Post.jsx]: It's kind of gross that this happens in `render`. But I know that was already like that. We should clean it up later.
