### PR TITLE
Revert "add test for the AppReducer (#2186)"

### LINKED ISSUE #2295: Master is not working under load.

### PR DESCRIPTION
**Pull request by gl2748**
Fixes #2295 

This reverts commit c1e7fbb01f48e57b5cd64ac4e612ba0cf82bec25.

### CODE REVIEW

File: src/app/redux/SagaShared.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ import tt from 'counterpart';
 import { api } from '@steemit/steem-js';
 
 import * as globalActions from './GlobalReducer';
-import * as appActions from './AppReducer';
```
Comment (relativityboy) [inline src/app/redux/SagaShared.js]: From the previous PR.. this might be the culprit
