### PR TITLE
Community - Fix 'transfer' page aliases

### LINKED ISSUE #3481: Weird links redirect issue, (at least two bugs)
click here
image

end up there https://steemit.com/steemit/@gmichelbkk/curation-rewards-explained-simply

image

remove the tag

image

end up here 

image
image

then find the post, click here

image

Works

image

Going to link directly desn't work.

image

### PR DESCRIPTION
**Pull request by roadscape**
From @quochuy #3482:

> Fixes #3481
>
> This bug would have affected all posts that have a title starting with "Curation Rewards" or "Author Rewards"

### CODE REVIEW

File: src/app/utils/steemApi.js [hunk 1]
```diff
@@ -15,10 +15,12 @@ export async function getStateAsync(url) {
     if (url === '') url = 'trending';
 
     // curation and author rewards pages are alias of `transfers`
-    if (url.indexOf('/curation-rewards') !== -1)
+    // @TODO: maybe remove these all together as Condenser should redirect them to Wallet?
+    if (url.match(/^@.*?\/curation-rewards$/) !== null) {
```
Comment (JonathanPorta) [inline src/app/utils/steemApi.js]: This would be a great place for a test. ;)

**Comment by roadscape** [comment]
Thanks @quochuy!
