### PR TITLE
fix mentions embedded within naked comment urls

### LINKED ISSUE #2556: comment URLs can get munged in render
A valid URL to a comment gets transformed into a broken link.

```
https://steemit.com/spam/@test-safari/34gfex-december-spam#@test-safari/re-test-safari-34gfex-december-spam-20180110t234627522z
```

Rendered as:

image

-------

## Minimal failing test case

Seems as though `#` followed by `@` causes it

```
https://steemit.com/foo#bar

https://steemit.com/foo#@bar
```

image

## To reproduce

Paste the valid comment URL `https://steemit.com/spam/@test-safari/34gfex-december-spam#@test-safari/re-test-safari-34gfex-december-spam-20180110t234627522z` into https://steemit.com/submit.html

### PR DESCRIPTION
**Pull request by roadscape**
Resolves #2556 (plus another found bug which is the 2nd added test case)

#### Case 1

Paste the valid comment URL `https://steemit.com/spam/@test-safari/34gfex-december-spam#@test-safari/re-test-safari-34gfex-december-spam-20180110t234627522z` into https://steemit.com/submit.html and see that the resulting URL is munged and the username within it is linked

#### Case 2

Paste `valid mention match but invalid username..@usernamewaytoolong` into https://steemit.com/submit.html and see that one of the period is missing even though the username did not get linked.

### CODE REVIEW

File: src/shared/HtmlReady.js [hunk 1]
```diff
@@ -268,7 +268,7 @@ function linkify(content, mutate, hashtags, usertags, images, links) {
     // usertag (mention)
     // Cribbed from https://github.com/twitter/twitter-text/blob/v1.14.7/js/twitter-text.js#L90
     content = content.replace(
-        /(^|[^a-zA-Z0-9_!#$%&*@＠\/]|(^|[^a-zA-Z0-9_+~.-\/]))[@＠]([a-z][-\.a-z\d]+[a-z\d])/gi,
+        /(^|[^a-zA-Z0-9_!#$%&*@＠\/]|(^|[^a-zA-Z0-9_+~.-\/#]))[@＠]([a-z][-\.a-z\d]+[a-z\d])/gi,
```
Comment (gl2748) [inline src/shared/HtmlReady.js]: This regex is intense, i understand it comes from twitter.
